// GMTK Game Jam 2025

#pragma once

#include "NativeGameplayTags.h"

namespace SpaceshipGameplayTags
{
	/*Input Tags*/
	GMTK25_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Throttle);
	GMTK25_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Turn);
	GMTK25_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Strafe);

	GMTK25_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip_Right_Tool);
	GMTK25_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Unequip_Right_Tool);

	GMTK25_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip_Left_Tool);
	GMTK25_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Unequip_Left_Tool);
	/*Player Tags*/
	GMTK25_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	GMTK25_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);

	GMTK25_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Tool_Drill);

	GMTK25_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Tool);
	GMTK25_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Tool);


}